### PR TITLE
add initial icons

### PR DESCRIPTION
**Pull request by Aman9das**

### CODE REVIEW

**Comment by Donnnno** [comment]
Great work here! Are these all the available icons?

**Comment by Aman9das** [comment]
Yes you're right i had missed some of the icons...

So I think there's no harm in having extra icons. And I suppose we can use some scripts to fill the other categories.. I will look into it tonight.. :)

But full disclosure i don't have linux, we'll need a third person down the road for testing.. (i use dad's computer, don't have own rn)

I think we should also copy all the symlinks from some popular icon themes.. 

for example firefox.svg is called by many other symlinks

firefox-default.svg
firefox-icon.svg
org.mozilla.firefox.svg

**Comment by Aman9das** [comment]
Yes you're right i had missed some of the icons...

So I think there's no harm in having extra icons. And I suppose we can use some scripts to fill the other categories.. I will look into it tonight.. :)

But full disclosure i don't have linux, we'll need a third person down the road for testing.. (i use dad's computer, don't have own rn)

I think we should also copy all the symlinks from some popular icon themes.. 

for example firefox.svg is called by many other symlinks

firefox-default.svg
firefox-icon.svg
org.mozilla.firefox.svg

**Comment by Donnnno** [comment]
> So I think there's no harm in having extra icons. And I suppose we can use some scripts to fill the other categories.. I will look into it tonight.. :)

Yeah, exactly!

> But full disclosure i don't have linux, we'll need a third person down the road for testing.. (i use dad's computer, don't have own rn)

I don't have Linux either haha, I think @joelchrono12 already offered to help with that :^)

**Comment by joelchrono12** [comment]
Yeah I can check how it looks on my machine, just let me know when can I test it, I think there are some things that need to be done first tho

**Comment by Donnnno** [comment]
Great!

**Pull request merged**
